console.log("###########################")
console.log("#                         #")
console.log("#            ↑            #")
console.log("#       select page       #")
console.log("#                         #")
console.log("###########################")